### ISSUE TITLE
Install fails (non-informative error message)

### ISSUE THREAD

**Issue by nickeubank** [rgiordan/zaminfluence#17]
Hello! I'm trying to use `zaminfluence` in 3.6.3 on macOS 11.3.1, but when I try and install it with:

```r
library("devtools")
devtools::install_github("https://github.com/rgiordan/zaminfluence/",
                           ref="master",
                           subdir="zaminfluence",
                           force=TRUE)
```

I'm getting:

```
Downloading GitHub repo rgiordan/zaminfluence@master

pillar  (1.6.0 -> 1.6.1) [CRAN]
tibble  (3.1.1 -> 3.1.2) [CRAN]
stringi (1.6.1 -> 1.6.2) [CRAN]
Installing 3 packages: pillar, tibble, stringi

Installing packages into ‘/Users/Nick/Library/R/3.6/library’
(as ‘lib’ is unspecified)


  There are binary versions available but the source versions are later:
        binary source needs_compilation
pillar   1.6.0  1.6.1             FALSE
tibble   3.1.1  3.1.2              TRUE
stringi  1.6.1  1.6.2              TRUE

installing the source packages ‘pillar’, ‘tibble’, ‘stringi’

✔  checking for file ‘/private/var/folders/tj/s8f2_ks15h315z5thvtnhz8r0000gp/T/Rtmpgg3QHO/remotes82c515f71e4c/rgiordan-zaminfluence-ea89795/zaminfluence/DESCRIPTION’
─  preparing ‘zaminfluence’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘zaminfluence_0.0.0.9000.tar.gz’
Installing package into ‘/Users/Nick/Library/R/3.6/library’
(as ‘lib’ is unspecified)

Warning message in i.p(...):
“installation of package ‘/var/folders/tj/s8f2_ks15h315z5thvtnhz8r0000gp/T//Rtmpgg3QHO/file82c596be1aa/zaminfluence_0.0.0.9000.tar.gz’ had non-zero exit status”
```

Any suggestions? Unfortunately it's a little too vague for me to troubleshoot...

**Comment by rgiordan** [comment]
Sorry, that's not a lot of information for me, either.  There's a [verbose option for install_github](https://www.rdocumentation.org/packages/ghit/versions/0.2.18/topics/install_github), you could at least start with that.

**Comment by nickeubank** [comment]
This at all helpful? 

![image](https://user-images.githubusercontent.com/9683693/118685788-624a0c80-b7d1-11eb-9ac1-fac47ccd3c13.png)

Didn't add much...

(Sorry, I usually spend my time in Python, so I'm little less familiar with R install debugging)

**Comment by rgiordan** [comment]
Though I think it's likely that you can get more information out of the install process, it'll be more effective for you to Google around and try stuff than for me to do it for you!  If you do narrow it down to a problem with `zaminfluence`, please do follow up on this issue and I'll try to fix it.

**Comment by nickeubank** [comment]
Oh, i mean it's `zaminfluence` I think -- I can install everything else without problems. This is the only place I'm running into issues.

**Comment by nickeubank** [comment]
(Not asking you to do my homework -- just trying to install your package and finding it's failing, while I'm able to install anything else I want, and the package doesn't appear designed to give informative install error messages, so I'm here. If you think this is not a zaminfluence issue for some reason, happy to go dig anywhere else)

**Comment by rgiordan** [comment]
I see what you're saying, it could well be `zaminfluence` that is a problem.  Sadly, R package authors don't have any control over the messaging during installation (AFAIK), and, as you guessed, the output you're showing me doesn't tell me anything actionable on my end.  Also, sadly, I'm not very experienced debugging install issues on other folks' systems, and will just be googling how to get more information, like you.

But if you're stuck, maybe I can make some suggestions.  Can you try cloning the repo and installing using `devtools::install_local` instead of `devtools::install_github` and see whether that works?

**Comment by nickeubank** [comment]
OK -- I'll keep dabbling. 

Same issue. with `install_local`.

**Comment by nickeubank** [comment]
Got it!

The package loads `gridExtra` but doesn't list it as a dependency, so it fails during compilation.

**Comment by nickeubank** [comment]
For future reference, downloading, compressing into a tar.gz, and running `R CMD INSTALL zaminfluence.tar.gz` results in getting more informative error messages.

**Comment by rgiordan** [comment]
Fantastic!  Sorry I wasn't more help, and thanks for following up with  PR!
