### ISSUE TITLE
Typos in readme example

### ISSUE THREAD

**Issue by maswiebe** [rgiordan/zaminfluence#33]
- `library(GridExtra)` should be `library(gridExtra)`
- `num_obs` is missing
- `pivot_wider(-method, names_from=method, values_from=value)` should be `pivot_wider(names_from=method, values_from=value)`?

**Comment by rgiordan** [comment]
Thanks for pointing these out!  I think the `pivot_wider` syntax changed recently and I did indeed forget to update the README.

**Comment by rgiordan** [comment]
Fixed in https://github.com/rgiordan/zaminfluence/commit/9f96b1899a6f186d6c7fc36f6324117f2d811a61
