### ISSUE TITLE
Code for change in magnitude, but not sign or coefficient

### ISSUE THREAD

**Issue by weiyangtham** [rgiordan/zaminfluence#44]
Hi, I'm interested in using this in a case where the sign and significance of a coefficient is unlikely to change, but I'd still like to know how much the magnitude changes in response to various values of $\alpha$. Is there a way to do it with the package in its current form? Sorry if it was already in the documentation and I missed it.

**Comment by rgiordan** [comment]
I apologize for not monitoring the issues more closely!

Of course, if you are looking at the magnitude of just a single coefficient, then the change in norm is just the max absolute value of the most negative change and the most positive change. 

But sometimes you want to add up the contributions of different components of a vector, which each may be positive or negative.  That is, you'd like the sensitivity of the norm of a vector.  But I'm afraid the sensitivity of the norm of a vector is not such an easy problem. [See this blog post for some analysis.](https://rgiordan.github.io/differentiability/2021/07/20/norms.html)
